#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          27

bspc config focused_border_color '#088600'
bspc config presel_feedback_color '#088600'

bspc rule -a Gimp desktop='^3'
bspc rule -a firefox desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a Gnome-screenshot state=floating
bspc rule -a Screenkey manage=off

$HOME/.config/bspwm/autostart
